const FETCH_PERSON_ADDRESS = 'FETCH_PERSON_ADDRESS';
const FETCH_PERSON_ADDRESS_SUCCESS = 'FETCH_PERSON_ADDRESS_SUCCESS';
const FETCH_PERSON_ADDRESS_ERROR = 'FETCH_PERSON_ADDRESS_ERROR';

const FETCH_PERSON = ' FETCH_PERSON';
const FETCH_PERSON_SUCCESS = 'FETCH_PERSON_SUCCESS';
const FETCH_PERSON_ERROR = 'FETCH_PERSON_ERROR';

